using Pkg

Pkg.add("DifferentialEquations")
Pkg.add("CUDA")
Pkg.add("JSON")
Pkg.add("PlotlyJS")
Pkg.add("LoopVectorization")
Pkg.add("Symbolics")
Pkg.add("Interpolations")
Pkg.add("LinearAlgebra")
Pkg.add("SparseArrays")
Pkg.add("Dates")
Pkg.add("CSV")
Pkg.add("DataFrames")
Pkg.add("Logging")
Pkg.add("TerminalLoggers")
Pkg.add("JLD2")
Pkg.add("HDF5")
Pkg.add("LoggingExtras")
Pkg.add("Nettle")